version: '3.6'

x-kolibri-service: &kolibri-service
  build:
    context: .
    dockerfile: .dockerfile

services:

  kolibri-telegram-bot:
    << : *kolibri-service
    container_name: kolibri-telegram-bot
    image: kolibri-telegram-bot
    ports:
      - 8080:8080
    env_file:
      - ./kolibri-telegram-bot/.env
    command: ./start.sh telegram-bot

  kolibri-commandline-utility:
    << : *kolibri-service
    container_name: kolibri-commandline-utility
    image: kolibri-commandline-utility
    env_file:
      - ./kolibri-commandline-utility/.env
    command: ./start.sh commandline-utility

  proxy:
    image: nginx:1.17.10
    container_name: proxy
    ports:
      - 80:80
      - 81:81
      - 443:443
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf:ro
    command: nginx -g 'daemon off;'

networks:
  default:
    name: kolibri-network
