version: '3.6'

x-kolibri-service: &kolibri-service
  build:
    context: .
    dockerfile: .dockerfile

services:

  kolibri-telegram-bot:
    << : *kolibri-service
    container_name: kolibri-telegram-bot
    image: kolibri-telegram-bot
    ports:
      - 8080:8080
    env_file:
      - ./kolibri-telegram-bot/.env
    command: ./start.sh telegram-bot

  kolibri-commandline-utility:
    << : *kolibri-service
    container_name: kolibri-commandline-utility
    image: kolibri-commandline-utility
    env_file:
      - ./kolibri-commandline-utility/.env
    command: ./start.sh commandline-utility

networks:
  default:
    name: kolibri-network
