version: '3.6'

services:

  kolibri-database:
    container_name: kolibri-database
    image: postgres:13
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: kolibri
      POSTGRES_USER: kolibri
      POSTGRES_PASSWORD: kolibri
    volumes:
      - /var/pg/kolibri-db:/var/lib/postgresql/data

  kolibri-api:
    build:
      context: .
      dockerfile: kolibri-api/.dockerfile
    container_name: kolibri-api
    image: kolibri-api
    ports:
      - 1100:1100
    volumes:
      - /var/log:/var/log
    env_file:
      - ./kolibri-api/.env
    command: java -jar app.jar

  kolibri-scheduler:
    build:
      context: .
      dockerfile: kolibri-scheduler/.dockerfile
    container_name: kolibri-scheduler
    image: kolibri-scheduler
    volumes:
      - /var/log:/var/log
    env_file:
      - ./kolibri-scheduler/.env
    command: java -jar app.jar

  kolibri-consumer:
    build:
      context: .
      dockerfile: kolibri-consumer/.dockerfile
    container_name: kolibri-consumer
    image: kolibri-consumer
    volumes:
      - /var/log:/var/log
    env_file:
      - ./kolibri-consumer/.env
    command: java -jar app.jar

networks:
  default:
    name: kolibri-network
