version: '3.6'

services:

  kolibri-telegram-bot:
    build:
      context: .
      dockerfile: kolibri-telegram-bot/.dockerfile
    container_name: kolibri-telegram-bot
    image: kolibri-telegram-bot
    ports:
      - 8080:8080
    volumes:
      - /var/log:/var/log
    env_file:
      - ./kolibri-telegram-bot/.env
    command: java -jar app.jar

  kolibri-commandline-utility:
    build:
      context: .
      dockerfile: kolibri-commandline-utility/.dockerfile
    container_name: kolibri-commandline-utility
    image: kolibri-commandline-utility
    volumes:
      - /var/log:/var/log
    env_file:
      - ./kolibri-commandline-utility/.env
    command: java -jar app.jar

  proxy:
    image: nginx:1.17.10
    container_name: proxy
    ports:
      - 80:80
      - 81:81
      - 443:443
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./proxy/fullchain.pem:/etc/ssl/certs/fullchain.pem:ro
      - ./proxy/privkey.pem:/etc/ssl/private/privkey.pem:ro
    command: nginx -g 'daemon off;'

networks:
  default:
    name: kolibri-network
